//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phoneBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phonebook
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Departament { get; set; }
        public string Unit { get; set; }
        public string Position { get; set; }
        public string Number { get; set; }
        public string Building { get; set; }
        public string Cabinet { get; set; }
        public Nullable<byte> ImageData { get; set; }
    }
}
